// example/micro-father/src/App.tsx
import React, { useEffect } from "react";
import {
  sendStateToChild,
  registerChildStateListener,
  registerListener,
  removeChildStateListener,
  removeListener,
} from "@bridge-start/micro-front-father";
import { createBrowserHistory } from "history";

const history = createBrowserHistory();

const SendWhileMount = () => {
  useEffect(() => {
    const handleMount = () => {
      sendStateToChild({ name: "init", params: { name: "zx", from: "father" } });
    };
    registerListener("AfterMount", handleMount);
    return () => {
      removeListener("AfterMount", handleMount);
    };
  }, []);
  return null;
};

const FeedbackDemo = () => {
  const handle = () => {
    sendStateToChild({
      name: "login",
      params: { token: `token${new Date().getTime()}`, from: "father" },
    });
  };
  useEffect(() => {
    registerChildStateListener(handle, "login-request");
    return () => {
      removeChildStateListener(handle);
    };
  }, []);
  return null;
};

const Header = () => {
  return (
    <div>
      <button onClick={() => history.push("/react")}>react-child</button>
    </div>
  );
};

export const App = () => {
  return (
    <div>
      Father content
      <Header />
      <SendWhileMount />
      <FeedbackDemo />
    </div>
  );
};

// example/micro-father-vue/src/App.vue
<template>
  <div>
    Father content vue
    <div>
      <button @click="handleReactChildClick">react-child</button>
      <button @click="handleVueChildClick">react-vue</button>
    </div>
  </div>
</template>

<script>
import { createBrowserHistory } from "history";
import {
  registerChildStateListener,
  registerListener,
  removeChildStateListener,
  removeListener,
  sendStateToChild,
} from "@bridge-start/micro-front-father";
const history = createBrowserHistory();
export default {
  name: "App",
  mounted() {
    registerListener("AfterMount", this.handleMount);
    registerChildStateListener(this.handleChildState, "login-request");
  },
  beforeDestroy() {
    removeListener("AfterMount", this.handleMount);
    removeChildStateListener(this.handleChildState);
  },
  methods: {
    handleReactChildClick() {
      history.push("/react");
    },
    handleVueChildClick() {
      history.push("/vue");
    },
    handleMount() {
      sendStateToChild({ name: "init", params: { name: "zx", from: "father" } });
    },
    handleChildState() {
      sendStateToChild({
        name: "login",
        params: { token: `token${new Date().getTime()}`, from: "father" },
      });
    },
  },
};
</script>

<style scoped></style>
